[package]
name = "variables"
version = "2.3.4"
authors = ["Frank Li <frankli.consult@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
